---
- name: Add HHVM repository key
  shell: wget -O - http://dl.hhvm.com/conf/hhvm.gpg.key | sudo apt-key add -

- name: Add HHVM repository
  shell: echo deb http://dl.hhvm.com/ubuntu trusty main | sudo tee /etc/apt/sources.list.d/hhvm.list

- name: Update APT
  apt: update_cache=yes

- name: Install HHVM
  apt: pkg=hhvm state=latest

- name: Start HHVM
  service: name=hhvm state=running enabled=yes
  