---

- name: Install Default Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - git
    - vim

- name: Configure the timezone
  sudo: yes
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  sudo: yes
  file: src=/usr/share/zoneinfo/{{timezone}} dest=/etc/localtime state=link force=yes backup=yes
