---
  app_name: spellstruck
  server_name: spellstruck.dev.nl www.spellstruck.dev.nl
  app_document_root_base: /vagrant/www
  app_document_root: "{{ app_document_root_base }}/{{ app_name }}/public"
  server_document_root_base: /var/www
  server_document_root: "{{ server_document_root_base }}/{{ app_name }}/public"
  timezone: Europe/Amsterdam
