---
- name: Install Nginx
  sudo: yes
  apt: pkg=nginx state=latest

- name: Change default nginx site
  sudo: yes
  template: src={{ nginx_vhost_template }} dest={{ nginx_vhost_path }}/{{ nginx_vhost_file }}
  notify: restart nginx