---
- hosts: all
  sudo: true
  vars:
    app_name: spellstruck
    web_server: nginx
    servername: spellstruck.dev.nl www.spellstruck.dev.nl
    timezone: Europe/Amsterdam
  vars_files:
    - vars/common.yml
    - vars/mysql.yml
    - vars/nginx.yml
  roles:
    - init
    - nginx
    - hhvm
    - mysql
    - composer
