- name: Install Composer
  shell: wget -nc https://getcomposer.org/installer && hhvm -v ResourceLimit.SocketDefaultTimeout=30 -v Http.SlowQueryThreshold=30000 installer && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
